### ISSUE TITLE
NRF9160 Toolchain setup

### ISSUE THREAD

**Issue by ramb0t** [golioth/docs#111]
On https://docs.golioth.io/hardware/nrf91/quickstart/set-up-zephyr/

I think the command should be  `west init -m https://github.com/nrfconnect/sdk-nrf --mr v1.7.1 ~/zephyr-nrf ` to get the latest version ? as per https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/gs_installing.html

Unless you shouldn't be using the latest version and rather sticking to V1.7.0 rc2 of the nrf toolchain?

**Comment by 0Grit** [comment]
@golioth/firmware

**Comment by mniestroj** [comment]
Command is already up to date on linked documentation page.
