### ISSUE TITLE
Linux ESP32 quickstart on Ubuntu

### ISSUE THREAD

**Issue by vitprajzler** [golioth/docs#130]
I observed some challenges that a Ubuntu user needs to solve on his own when following the quickstart:

- The cmake version in the apt repo is older than what `west build` needs. I installed newer version via snap. When I then run the apt cmake install from the quickstart, it installs the older version again and due to the order of `$PATH` directories, ends up being used by default. The docs could outline how to get a cmake that works with west build 
- the quickstart uses `~/zephyrproject` as the directory to install into. Given the variety of users of the docs, I'd say a more generic approach to the path definition would be easier to work with. The docs could define a variable (`$GOLIOTH_PROJECT_PATH`) at the start that then can be used in subsequent commands
- when `west espressif install` finishes, it lists the specific exports the user should perform in its environment. The guide could instruct users to follow those specific exports, and just add whichever commands are still needed on top of them (in my environment, the $PATH change wasn't required)

**Comment by szczys** [comment]
I've had a similar experience as you outline here and agree with your suggested fixes.

Also, the exports for paths need to be updated in the docs. The `west espressif install` instructs you on the correct exports but they do not match what we have:
![image](https://user-images.githubusercontent.com/367685/147974290-49e07b38-c60b-4afa-b2e9-58df5995f6b1.png)

**Comment by szczys** [comment]
I've just solved the cmake issue by compiling from source. This was really easy and painless except it took a long time to compile (~20 minutes):
```
cmake --version

cmake version 3.16.3

sudo apt install build-essential libssl-dev
./bootstrap
make
sudo make install

cmake --version

cmake version 3.22.1
```

cmake source download page is here: https://cmake.org/download/

**Comment by vitprajzler** [comment]
> The west espressif install instructs you on the correct exports but they do not match what we have:

That was the same for me. I didn't try if our instructions work, but the `west espressif install` did.

Great that building cmake from source is an easy process!
