### ISSUE TITLE
west patch throws error in nRF91 quickstart

### ISSUE THREAD

**Issue by szczys** [golioth/docs#134]
```
(.venv) mike@krusty ~/zephyr-nrf/nrf $ west patch
usage: west [-h] [-z ZEPHYR_BASE] [-v] [-V] <command> ...
west: error: argument <command>: invalid choice: 'patch' (choose from 'init', 'update', 'list', 'manifest', 'diff', 'status', 'forall', 'help', 'config', 'topdir', 'selfupdate', 'ncs-loot', 'ncs-compare', 'completion', 'boards', 'build', 'sign', 'flash', 'debug', 'debugserver', 'attach', 'zephyr-export', 'spdx')
```
Is the `west patch` step no longer needed?

https://github.com/golioth/docs/blob/3499a5e5579f62391127a09a22b6aa1b616e05c7/docs/partials/install-nrf91-sdk.md?plain=1#L32

**Comment by vancefarren** [comment]
I can't remember what 'patch' does.  @mniestroj , do we still need this?

**Comment by mniestroj** [comment]
`west patch` is no longer needed. See https://github.com/golioth/zephyr-sdk/pull/144 for change in SDK README file.
