### ISSUE TITLE
ZEPHYR_TOOLCHAIN_VARIANT not set when following nRF91 quickstart guide

### ISSUE THREAD

**Issue by szczys** [golioth/docs#135]
For the ESP32 quickstart, these environmental variables are set, but this step is not included in the n91 guide resulting in error:

```
-- ZEPHYR_TOOLCHAIN_VARIANT not set, trying to locate Zephyr SDK
CMake Error at /home/mike/zephyr-nrf/zephyr/cmake/verify-toolchain.cmake:79 (find_package):
  Could not find a package configuration file provided by "Zephyr-sdk"
  (requested version 0.12) with any of the following names:

...
```

**Comment by szczys** [comment]
This Nordic page suggests some answers (bullet point 6):
https://devzone.nordicsemi.com/guides/nrf-connect-sdk-guides/b/software/posts/nrf-connect-sdk-build-fails

As do the Zephry docs:
https://docs.zephyrproject.org/latest/getting_started/toolchain_3rd_party_x_compilers.html#

I was not able to find a compiler that was installed during the quickstart. However, I know I already have an arm-none-eabi- toolchain on my machine at `/usr/bin/` so I pointed it there.

This is what I did to get the minimal sample to compile:
```
export ZEPHYR_TOOLCHAIN_VARIANT="gnuarmemb"
export GNUARMEMB_TOOLCHAIN_PATH="/usr"
cd ~/zephyr-nrf/zephyr
west build -p auto -b  circuitdojo_feather_nrf9160ns samples/basic/minimal
```

Do we need to add instructions on installing the compiler?

**Comment by vancefarren** [comment]
Are you installing using the virtual python environment, or the global setup?

**Comment by szczys** [comment]
@vancefarren I'm using the virtalenv

After conferring with @ChrisGammell he says the docs should direct users to the Zephyr toolchain install step and that there is likely an open PR with this information in it already:
https://docs.zephyrproject.org/latest/getting_started/index.html#install-a-toolchain

**Comment by szczys** [comment]
After installing the toolchain I am able to compile without needing to set any environment variables. However, I am not able to flash the chip:

```
(.venv) mike@krusty ~/zephyr-nrf/zephyr $ west flash
-- west flash: rebuilding
[0/11] Performing build step for 'spm_subimage'
ninja: no work to do.
-- west flash: using runner nrfjprog
FATAL ERROR: required program nrfjprog not found; install it or add its location to PATH
```

@ChrisGammell is it also necessary to install nRF commandline tools as a separate step to get `nrfjprog`?

* https://docs.zephyrproject.org/1.14.0/guides/tools/nordic_segger.html
* https://www.nordicsemi.com/Products/Development-tools/nrf-command-line-tools/download

**Comment by szczys** [comment]
In the [Flashing an nRF91 with Samples](https://docs.golioth.io/hardware/nrf91/quickstart/flash-sample#flashing-the-device) page it addressing this issue:

> If this command fails ensure that the nRF Command Line tools and Jlink Software and Documentation Pack are downloaded and installed on the development system.

This needs to be moved to the [Set up Zephyr for nRF91](https://docs.golioth.io/hardware/nrf91/quickstart/set-up-zephyr) page so that `west flash` doesn't fail.

**Comment by szczys** [comment]
I've installed the cli programming tools (steps below because you will need them for j-link programmed boards) but as @ChrisGammell suggested, this CircuitDojo nRF91 Feather board is not found because it's not a j-link device. This complicates the quickstart, and we should find a solution that makes it clear to the user what they need to do to flash this versus something like the DK that (should) work with just `west flash`

### nRF CLI tool installation

Download the package [here](https://www.nordicsemi.com/Products/Development-tools/nrf-command-line-tools/download) and unpack the archive

```
sudo dpkg -i JLink_Linux_V758b_x86_64.deb
sudo dpkg -i nrf-command-line-tools_10.15.1_amd64.deb
```
