### ISSUE TITLE
Update documentation to use the new Zephyr toolchain

### ISSUE THREAD

**Issue by beriberikix** [golioth/docs#172]
https://github.com/zephyrproject-rtos/sdk-ng/releases/tag/v0.14.0. See also golioth/zephyr-sdk#179.

The official toolchain provided by Zephyr was recently migrating to a new packaging and distribution system. This should have no affect on Linux (but we should verify) but introduces official packages for macOS & Windows. This is a significant improvement on the user experience for users on macOS & Windows.

We should update the documentation to use the new toolchain consistently. 

Note: the Espressif toolchain is still separate, but there is a [draft PR](https://github.com/zephyrproject-rtos/sdk-ng/pull/426) that will add it to the new distribution. This will be benefit all three platforms.

**Comment by beriberikix** [comment]
Okay, so the tricky parts is that currently macOS & Windows are only the compilers, not the programmers. So I had to manually install dfu-util, bossac, etc. on Windows but _they do_ work. So while it's not worse than the current path, it's still missing those packages.

Should we update the documentation now or wait until the host tools land as well?

**Comment by szczys** [comment]
We've updated this a few times since this conversation, most recently #298 so I think this issue is resolve. Please reopen if there is still a lack of macOS/Windows programmers.
