### ISSUE TITLE
Setup up redirects for pages that moved in recent update to verification levels

### ISSUE THREAD

**Issue by beriberikix** [golioth/docs#192]
In #190 we updated boards to match our new verification levels. Unfortunately Docusaurus doesn't automatically handle redirects when pages are moved. Google will eventually update SEO but links to our docs will be broken. We should add 301 redirects in Firebase for the time being: https://firebase.google.com/docs/hosting/full-config#redirects

**Comment by szczys** [comment]
Since this is more than a year old, I assume search engines have updates to new links and removed broken ones.
