### ISSUE TITLE
Goliothctl windows download should be .zip or .exe, not .tar.gz

### ISSUE THREAD

**Issue by beriberikix** [golioth/docs#27]
https://docs.golioth.io/docs/guides/quickstart/installing

Currently we provide the Windows builds in the .tar.gz format. This is common for Linux/Posix OSes but not Windows. Windows binaries should be distributed as either .zip or .exe.

**Comment by ChrisGammell** [comment]
@alvarowolfx has this changed yet on the go releaser? I just clicked the link on the binary download page and saw that `goliothctl` is still downloading as a .tar.gz

**Comment by szczys** [comment]
This was fixed with #182
