### ISSUE TITLE
Package Manager works in Linux as well!

### ISSUE THREAD

**Issue by arijitdas123student** [golioth/docs#28]
Just wanted to bring this up that the [Work in progress] Homebrew [package manager](https://docs.golioth.io/docs/guides/quickstart/installing/#package-managers) not only works for [macOS](https://docs.golioth.io/docs/guides/quickstart/installing/#macos-homebrew) but for Linux (tested on Ubuntu 20.04 and WSL 2) as well!
Good job guys! 👍🏼

**Comment by ChrisGammell** [comment]
This is now possible natively using our linux package builds, see here: https://docs.golioth.io/getting-started/installing/packages
