### ISSUE TITLE
Add other useful info to 404 page

### ISSUE THREAD

**Issue by ChrisGammell** [golioth/docs#311]
Our 404 page is currently the built-in version from Docusaurus. If possible, we should add relevant links and an admonition to use search if people can't find what they're looking for.

**Comment by ChrisGammell** [comment]
This is what it currently looks like on prod: 
![image](https://github.com/golioth/docs/assets/1212045/6d16997c-2fa6-4088-b01b-89e4df9110c8)

**Comment by szczys** [comment]
Duplicate of #53 

I'll add this to the next sprint.
