### ISSUE TITLE
sdk 0.9.0 tag doesn't exist?

### ISSUE THREAD

**Issue by maxd-nordic** [golioth/docs#338]
https://github.com/golioth/docs/blob/a19d9e0ff2a2433061c17d5173e8c4b8bd3611ca/docs/_partials-common/ncs-install-golioth-firmware-sdk-for-unix.md?plain=1#L6

I get this error:
```
FATAL ERROR: command exited with status 128: git clone --branch v0.9.0 https://github.com/golioth/golioth-zephyr-sdk.git /home/max/work/golioth-ncs-workspace/.west/manifest-tmp
```

**Comment by szczys** [comment]
Thanks for reporting. The URL in that command is incorrect. I have a change in a PR which should be merged to the live site in a few minutes. Apologies for this error!
