### ISSUE TITLE
`west` instructions should use "-p" for pristine builds

### ISSUE THREAD

**Issue by beriberikix** [golioth/docs#36]
Users run into errors if they don't do clean pristine builds. All examples should include -p. Currently instructs west build -b esp32 samples/hello and it should be west build -b esp32 samples/hello -p @ https://docs.golioth.io/docs/guides/esp32-quickstart/esp32-flash-sample#building-hello. I didn't look for all references but there are a few more in the guides and possible Reference > Zephyr SDK > Samples too.

**Comment by szczys** [comment]
Dropping this here for my own reference:
```
grep -Rn "west build" * | grep -v '\-p'
```
