### ISSUE TITLE
Support page missing our discord community

### ISSUE THREAD

**Issue by 0Grit** [golioth/docs#38]
https://docs.golioth.io/docs/support

![image](https://user-images.githubusercontent.com/24318071/131938838-b657479f-2c87-46cc-b2ad-d1af26ac2e73.png)

**Comment by szczys** [comment]
The support page no longer exists in Docs. We do mention Discord on the root page:
https://docs.golioth.io/

![image](https://user-images.githubusercontent.com/367685/167153243-81c4993f-6fa2-4e2a-beed-51f52a3cd098.png)
