### ISSUE TITLE
Dockerfile for development

### ISSUE THREAD

**Issue by 0Grit** [golioth/docs#42]
As a contributor/developer to the docs I would like to have the exact environment Golioth uses internally for doc development, so I can get right to the business of contributing and testing changes.

Solution: Dockerfile

**Comment by 0Grit** [comment]
I'll tend to #41 if someone else takes on this one. @ChrisGammell @alvarowolfx

**Comment by ChrisGammell** [comment]
@0Grit has this been implementing with the changes that allow editing via gitpod?

**Comment by 0Grit** [comment]
Yep
