### ISSUE TITLE
Docs Versioning

### ISSUE THREAD

**Issue by 0Grit** [golioth/docs#50]
Being a developer who is used to interacting with the Golioth ecosystem as reccomended by older versions of the documentation I want to be able to look at past versions of the docs (Especially since docusaurus supports this) so I can gain insight about how to change my behavior in accordance with the latest version of the docs.

I don't really want to search google and find old versions of the docs though. I might not realize that my search resulted in me looking at stale docs.

**Comment by 0Grit** [comment]
Mbed OS has this problem. Old versions of the docs come up and google they don't make the version number of the docs stick out enough.

**Comment by ChrisGammell** [comment]
Totally possible using Docusaurus, but we determined we're not ready for it yet, given the dynamic nature of our docs and platform currently. I think it's a good target to do that sort of thing once we're in GA and to consider docs in a beta state until then.

**Comment by ChrisGammell** [comment]
Not planning to implement this anytime soon, closing.
