### ISSUE TITLE
Move CoAP endpoint documentation under Reference

### ISSUE THREAD

**Issue by beriberikix** [golioth/docs#68]
Services describe the various Devices Services and how the work. Currently they also include reference documentation for the CoAP endpoints. Ex.

![image](https://user-images.githubusercontent.com/178376/137993796-a0d53316-ddca-4413-a7fc-c213f72e5572.png)

We should move them under Reference > Protocols > CoAP, similar to the current REST/OpenAPI reference.

**Comment by szczys** [comment]
I'm unsure what PR made this change, but the CoAP endpoints are no located in the Reference section: https://docs.golioth.io/reference/protocols/coap/lightdb
