### ISSUE TITLE
Add docs for Cloud sections

### ISSUE THREAD

**Issue by beriberikix** [golioth/docs#70]
We need docs that provide an overview, installation (if applicable) and basic usage for the following sections under Cloud:

- [ ] Console
- [ ] `goliothctl`
- [ ] `coap`

These are not intended to be reference guides (they should link to Reference where appropriate.)

**Comment by ChrisGammell** [comment]
I think we need to discuss this more with @alvarowolfx. The "services" are now under the Cloud section, but I am not sure what you're looking for here otherwise.
