### ISSUE TITLE
Update Quickstart to Remove HW ID Flag

### ISSUE THREAD

**Issue by keenanjohnson** [golioth/docs#75]
[As I was running through the Quickstart tutorial](https://docs.golioth.io/services/getting-started/manage-devices), I ran into an issue with creating my first device.

The quickstart says to create the device via this command:

`goliothctl device create --name "My first device" --hwId "DE:AD:BE:EF"`

However, running that command returns an error: "2021/11/01 15:45:38 failed to register device :rpc error: code = Unknown desc = hardware id already being used"

Chatting with @ChrisGammell in Discord, he mentioned that the hwID is no longer required and that it might be easiest to use the web Console instead of goliothctl.

Either way, it would be helpful to others in the future to update the quickstart accordingly.

**Comment by ChrisGammell** [comment]
Great, have a change in process, appreciate the feedback!

**Comment by keenanjohnson** [comment]
Great! Glad to be of help.
