### ISSUE TITLE
Quickstart vs Getting Started

### ISSUE THREAD

**Issue by 0Grit** [golioth/docs#77]
Is there a difference or do we need to settle on one term?

**Comment by beriberikix** [comment]
Good question. The way it is right now "Getting Started" is the universal starting point for anyone starting with Golioth, hence the top-level nav link. A "quickstart" is a type of article that is a "happy path" guide for a particular task. Ex. nRF91 getting to blinky, making a REST call in go, etc.

Is the terminology confusing? We've had a fair number of naming debates but happy to revisit!
