### ISSUE TITLE
Documentation site logo and nav header are very similar to our webpage logo and header

### ISSUE THREAD

**Issue by 0Grit** [golioth/docs#87]
![image](https://user-images.githubusercontent.com/24318071/141523902-c63ff40a-757b-4bd4-b304-994510456df5.png)

Is very similar to

![image](https://user-images.githubusercontent.com/24318071/141523932-f9af3eee-9087-4b33-95c9-d2b780cc57e1.png)

May be confusing to users. I got hung up for a second by it actually.

Should we add the word "Documentation" in the vicinity of the Golioth Logo to provide cleaner context?

**Comment by beriberikix** [comment]
👍 Good point. Not sure what to change it to exactly, but we should figure that out soon.
