### ISSUE TITLE
getting started documentation issues

### ISSUE THREAD

**Issue by titimoby** [golioth/docs#89]
# In  docs/docs/getting-started/4-create-project.md

1.  project creation issue

After using ```goliothctl project create --name "My first project"``` the documentation expects 
```
$ goliothctl project list[ ] 
id:"my-first-project" name:"My first project"
```
but I have
```
$ goliothctl project list
[*] id:"my-first-project-231c99"  name:"My first project"
```
Having a unique Id seems logical, but in that case, you can't use the next command suggested
`goliothctl config set projectId my-first-project`
the result is for me
```
$ goliothctl config set projectId my-first-project
[*] id:"my-first-project-231c99"  name:"My first project"
2021/11/15 17:35:45 no projects found with id my-first-project
```

2. Can't use the command provided with the copy button for project list

There is a nice command line zone that you can copy 
```
$ goliothctl project list
[ ] id:"my-first-project" name:"My first project"
```
but it is not very useful as you get the starting $ sign and the result line.
You can't paste and run.

**Comment by 0Grit** [comment]
@alvarowolfx @ChrisGammell

**Comment by szczys** [comment]
Thanks for reporting this issue. I considered the current state of the documentation. There is an admonishment when creating the project that the name must be unique.  Beyond that I think it is left to the user to understand that they need to substitute `my-first-project` with the name actually used to create the project. Perhaps using `<my-first-project>` would make it slightly more clear but then there's confusion on when or not to include the angle brackets in the command. I think the clearest option is to leave this as it stands.
